#!/usr/bin/env bash

set -ex

dir=$(dirname "$0")
test -n "$dir"
cd "$dir"

if [[ -d dist ]]; then
    rm -rf dist
fi
mkdir dist

cleanup() {
    rm -rf "$dir"/{teek,target,build,mystcl.egg-info}
}
trap cleanup EXIT

pushd python_module
for PYBIN in /opt/python/{cp35-cp35m,cp36-cp36m,cp37-cp37m}/bin; do
    if [[ ! -d $PYBIN ]]; then
        echo "This must be run inside the manylinux Docker container."
        exit 1
    fi

    export PYTHON_SYS_EXECUTABLE="$PYBIN/python"

   "$PYTHON_SYS_EXECUTABLE" -m pip install --upgrade setuptools setuptools-rust
   "$PYTHON_SYS_EXECUTABLE" setup.py bdist_wheel
   mv dist/* ../dist/
done
popd

for whl in dist/*.whl; do
    auditwheel repair "$whl" -w dist/
    rm "$whl"
done

git clone --no-checkout https://github.com/Akuli/teek

git -C teek checkout f0acc49
git -C teek apply ../teek.patch

for PYBIN in /opt/python/{cp35-cp35m,cp36-cp36m,cp37-cp37m}/bin; do
    export PYTHON_SYS_EXECUTABLE="$PYBIN/python"

   pushd python_module
   "$PYTHON_SYS_EXECUTABLE" setup.py install
   popd

   pushd teek
   "$PYTHON_SYS_EXECUTABLE" -m pip install \
        pytest \
        docutils sphinx \
        pillow reportlab svglib lxml beautifulsoup4

   CI=yes xvfb-run "$PYTHON_SYS_EXECUTABLE" -m pytest
   popd
done
