#!/usr/bin/env bash

for PYBIN in /opt/python/{cp35-cp35m,cp36-cp36m,cp37-cp37m}/bin; do
    export PYTHON_SYS_EXECUTABLE="$PYBIN/python"

    ( "${PYBIN}/pip" install -U setuptools setuptools-rust && "${PYBIN}/python" setup.py bdist_wheel ) || exit 1
done

for whl in dist/*.whl; do
    auditwheel repair "$whl" -w dist/ || exit 1
done
