#!/usr/bin/env bash

set -ex

if [[ -z $TWINE_USERNAME || -z $TWINE_PASSWORD ]]; then
    echo "No username or password set for twine."
    exit 1
fi

python3 -m pip install --upgrade twine
python3 -m twine upload dist/*
